- react/src/pages/Navigation.tsx
- react/src/pages/analysis/AnalysisInfoDialog.tsx
- react/src/pages/upload/FilesTable.tsx
- react/src/pages/upload/UploadDialog.tsx
- react/src/pages/upload/Uploads.tsx
Added form for entering metadata
> Upload form

- react/src/pages/ListItemRouterLink.tsx
- react/src/pages/Navigation.tsx
The page name now matches the page you are on. Closes #25
> update page name to match the current page

- flask/app/models.py
- flask/app/routes.py
Kevin's new fix for serialization
Closes #18
> Flask: GET /api/participants, /api/datasets, /api/analyses, /api/pipelines

- flask/app/config.py
- flask/app/routes.py
> Flask: add GET /api/enums

- react/src/pages/analysis/Analysis.tsx
Really small UX bug on the analysis page.
> Fix visibility button not working unless selected

- react/src/pages/analysis/CancelAnalysisDialog.tsx
- react/src/pages/dashboard/ParticipantTable.tsx
- react/src/pages/datasets/AnalysisRunnerDialog.tsx
- react/src/pages/datasets/DatasetTable.tsx
- react/src/pages/utils.tsx
Refactor SlideUpTransition from AnalysisInfoDialog and CancelAnalysisDialog for reuse
Refactor countArray and toKeyValue from ParticipantTable and DatasetTable for reuse
Closes #65
> Add utils.tsx

- flask/app/manage.py
> add datasets_analyses table to dummy data

- flask/app/routes.py
- flask/requirements-dev.txt
- flask/requirements.in
- flask/requirements.txt
Closes #45 
rebuild app container since `pandas` was added: `docker-compose build`
to test, `curl -X POST -H "Content-Type: text/csv" --data-binary @st_sample_upload.csv  localhost:5000/api/_bulk`
Example errors:
`
Error on line 1 - Invalid value for: "participant_type", current input is "FF" but must be one of ['Proband', 'Mother', 'Father', 'Sibling']%
`
`
Error on line 6: Invalid value for: "tissue_sample_type", current input is "SALOVA" but must be one of ['Blood', 'Saliva', 'Lymphocyte', 'Fibroblast', 'Muscle', 'Skin', 'Urine', 'Plasma', 'Unknown', 'Kidney']%
`
output:
```
[
{
"batch_id": null,
"capture_kit": null,
"condition": "Control",
"created": "Thu, 15 Oct 2020 13:36:38 GMT",
"created_by": 1,
"dataset_id": 4,
"dataset_type": "WES",
"extraction_protocol": "Something", …
```
> Flask: add POST /api/_bulk

- react/src/App.tsx
- react/src/pages/Navigation.tsx
- react/src/pages/dashboard/Dashboard.tsx
- react/src/pages/dashboard/ParticipantTable.tsx
Prune unused styles from Navigation
Align app bar menu icon and user profile icon with content below
Fix container margin consistency in Dashboard
Closes #78
> React: reduce font size, drawer width, app bar height

- flask/app/models.py
- flask/app/routes.py
The general serialization problem will be a separate issue
> Flask: fix PATCH /api/analyses/:id to accept string usernames

- flask/app/routes.py
Test: `curl -X POST -H "Content-Type: application/json"  -d '{"datasets" : [1, 2], "pipeline_id" : 1}' localhost:5000/api/analyses`
Expected Output:
```
{
"analysis_id": 3,
"analysis_state": "Requested",
"assignee": null,
"finished": null,
"notes": null,
"pipeline_id": 1,
"qsub_id": null,
"requested": "Tue, 20 Oct 2020 19:20:32 GMT",
"requester": 1,
"result_hpf_path": null,
"started": null,
"updated": "Tue, 20 Oct 2020 19:20:32 GMT",
"updated_by": 1
}
```
Before:
```
mysql> select * from datasets_analyses;
+------------+-------------+
| dataset_id | analysis_id |
+------------+-------------+
|          1 |           1 |
|          1 |           2 |
|          2 |           2 |
|          3 |           2 |
+------------+-------------+
mysql> select * from analysis; …
```
> Flask: POST endpoint for analyses /api/analyses

- react/src/pages/Navigation.tsx
> React: collapse navigation drawer by default

- react/src/pages/analysis/Analysis.tsx
- react/src/pages/dashboard/ParticipantTable.tsx
- react/src/pages/datasets/DatasetTable.tsx
- react/src/pages/upload/FilesTable.tsx
- react/src/pages/upload/UploadDialog.tsx
- react/src/pages/upload/UploadForm.tsx
Removed some unused dummy-data functions now that we're getting data remotely.
> React: tidy imports, fix compiler warnings

- react/src/pages/Notification.tsx
- react/src/pages/analysis/Analyses.tsx
- react/src/pages/analysis/AnalysisInfoDialog.tsx
- react/src/pages/utils.tsx
> React: hook up analysis table run / cancel analyses

- flask/app/models.py
- flask/app/routes.py
> Flask: add GET /api/analyses/:id

- react/src/pages/analysis/Analyses.tsx
- react/src/pages/datasets/DatasetInfoDialog.tsx
- react/src/pages/datasets/DatasetTable.tsx
- react/src/pages/datasets/DialogSections.tsx
- react/src/pages/participants/AnalysisTable.tsx
- react/src/pages/participants/SampleTable.tsx
- react/src/pages/utils.tsx
Closes #52. Layout is similar to #69
> React: Datasets modal; view details

- flask/app/routes.py
- react/src/pages/analysis/Analyses.tsx
- react/src/pages/datasets/AnalysisRunnerDialog.tsx
> React: hook up request analysis to backend

- react/src/pages/NotificationPopover.tsx
> React: add notification badge

- react/src/pages/AnalysisInfoDialog.tsx
- react/src/pages/analysis/Analyses.tsx
- react/src/pages/datasets/DialogSections.tsx
- react/src/pages/utils.tsx
Closes #88 
Layout is very similar to dialog for #109, and so this should be revisited for #119
> React: hook up analysis details to backend

- flask/app/__init__.py
- flask/app/families.py
closes #131 and unblocks #129
output:
```
curl --request GET  http:/0.0.0.0:5000/api/families
[
{
"created": "Tue, 03 Nov 2020 16:41:20 GMT", 
"created_by": 1, 
"family_codename": "1000", 
"family_id": 1, 
"participants": [
{
"affected": false, 
"created": "Tue, 03 Nov 2020 16:41:20 GMT", 
"created_by": 1, 
"month_of_birth": "Sun, 01 Feb 1970 00:00:00 GMT", 
"notes": "", 
"participant_codename": "AA003", 
"participant_id": 3, 
"participant_type": "Parent", 
"sex": "Female", 
"solved": null, 
"updated": "Tue, 03 Nov 2020 16:41:20 GMT", 
"updated_by": 1
}, 
{
"affected": false, 
"created": "Tue, 03 Nov 2020 16:41:20 GMT", 
"created_by": 1, 
"month_of_birth": "Thu, 01 Jan 1970 00:00:00 GMT", 
"notes": "", 
"participant_codename": "AA002", 
"participant_id": 2, 
"participant_type": "Parent", …
```
> Flask: family endpoints 

- flask/app/__init__.py
- flask/app/families.py
closes #132,  #133 , #134 
DELETE api/families/:id
```
curl --request DELETE http:/0.0.0.0:5000/api/families/1
Family has participants, cannot delete!%          
curl --request DELETE http:/0.0.0.0:5000/api/families/2
Deletion successful%                          
curl --request DELETE http:/0.0.0.0:5000/api/families/3
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.%                                
```
GET api/families/:id
```
curl --request GET  http:/0.0.0.0:5000/api/families/1
[
{
"created": "Tue, 03 Nov 2020 20:25:22 GMT", 
"created_by": 1, 
"family_codename": "1000", 
"family_id": 1, 
"participants": [
{
"affected": true, 
"created": "Tue, 03 Nov 2020 20:25:22 GMT", 
"created_by": 1, 
"month_of_birth": "Sat, 01 …
```
> Flask: add DELETE, PATCH, GET /api/families/:id

- flask/app/__init__.py
- flask/app/manage.py
- flask/app/participants.py
- flask/app/routes.py
closes #135 
Added participant with participant_id=4  in manage.py for testing deletion of a participant with no associated tissue samples.
> Flask: DELETE /api/participants/:id

- flask/app/manage.py
- flask/app/routes.py
closes #149
For testing purposes ,I modified manage.py so that TissueSample with tissue_sample_id=2 does not have any associated datasets and can be successfully removed. 
`curl -X DELETE http://localhost:3000/api/tissue_samples/2`
> Flask: add DELETE /api/tissue_samples/:id

- react/src/pages/Navigation.tsx
> React: Fix app bar height

- react/src/pages/addParticipants/AddParticipants.tsx
- react/src/pages/participants/SampleTable.tsx
- react/src/pages/utils/functions.tsx
- react/src/pages/utils/typings.tsx
- react/src/pages/utils/upload/DataEntryTable.tsx
> React: Add empty row button for data entry table

- .editorconfig
- .github/labels.yml
- .github/workflows/label.yml
> CI: add pull request labeller workflow

- flask/Dockerfile
- flask/app/madmin.py
- flask/tests/test_madmin.py
> Flask: add MinIO administration module

- react/src/pages/utils/upload/DataEntryTable.tsx
- react/src/pages/utils/upload/UploadUtils.tsx
> React Add participants: Checkbox cell for boolean headers

- flask/app/buckets.py
- flask/app/models.py
> Flask: Create MinIO unlinked files endpoint

- flask/app/routes.py
```
curl -X POST \
--data '{
"family_codename": "1001",
"participant_codename":"06332",
"tissue_sample" : "Blood",
"tissue_sample_type" :"Blood",
"dataset_type" : "WGS",
"condition": "GermLine",
"gender": "Male",
"participant_type": "Parent"
}' \
localhost:5000/api/_bulk
JSON must be in an array%   
```
```
curl -X POST \
--data '[{
"family_codename": "1001",
"participant_codename":"06332",
"tissue_sample" : "Blood",
"tissue_sample_type" :"Blood",
"dataset_type" : "WGS",
"condition": "GermLine",
"gender": "Male",
"participant_type": "Parent"
}]' \
localhost:5000/api/_bulk
```
```
curl -X POST -H "Content-Type: application/json"  --data '[
{
"family_codename": "1001",
"participant_codename":"1411", …
```
> Flask: extend _bulk endpoint to accept json

- react/src/pages/Notification.tsx
- react/src/pages/analysis/Analyses.tsx
- react/src/pages/datasets/AnalysisRunnerDialog.tsx
- react/src/pages/datasets/DatasetTable.tsx
- react/src/pages/participants/ParticipantTable.tsx
> React: Fix lint warnings

- .github/workflows/react.yml
- react/package.json
- react/src/pages/utils/upload/DataEntryTable.tsx
> CI: add frontend workflow

- flask/app/routes.py
closes #168
testing: 
```
from datetime import datetime
import requests
import json
tissue = {
"participant_id": 1,
"extraction_date": "0001-01-01T00:00:00-04:00",
"tissue_sample_type": "Blood",
"tissue_processing": "FreshFrozen",
"notes": "blahblah"
}
url = 'http://0.0.0.0:5000/api/tissue_samples'
result = requests.post(url, json = tissue)
r = result.json()
print(r)
```
> Flask: POST /api/tissue_samples

- flask/app/datasets.py
Closes #169
```
curl -X POST \
--data '{
"tissue_sample_id": "1",
"dataset_type": "CES",
"input_hpf_path": "/hpf/CES",
"notes": "blahblah",
"condition": "GermLine",
"extraction_protocol": "Something",
"capture_kit": "capture kit x",
"read_length": "150",
"read_type": "PairedEnd",
"discriminator": "dataset"
}' \
localhost:3000/api/datasets
```
returns
```
{
"batch_id": null, 
"capture_kit": "capture kit x", 
"condition": "GermLine", 
"created": "Mon, 16 Nov 2020 21:37:06 GMT", 
"created_by": 1, 
"dataset_id": 5, 
"dataset_type": "CES", 
"extraction_protocol": "Something", 
"input_hpf_path": "/hpf/CES", 
"library_prep_date": null, 
"library_prep_method": null, 
"notes": "blahblah", 
"read_length": 150, 
"read_type": "PairedEnd", 
"sequencing_centre": …
```
> Flask: POST /api/datasets

- flask/app/participants.py
closes #167 
* new participant codename for existing family
```
curl -D - -X POST \
-H "Content-Type: application/json" \
--data '{"family_id" : "1",
"participant_codename":"AA3",
"participant_type": "Parent",
"sex" : "Female"
}' \
localhost:5000/api/participants
HTTP/1.0 201 CREATED
Content-Type: application/json
Content-Length: 333
Location: http://localhost:5000/api/participants/13
Server: Werkzeug/1.0.1 Python/3.7.8
Date: Wed, 18 Nov 2020 15:16:05 GMT
{
"affected": null, 
"created": "Wed, 18 Nov 2020 15:16:05 GMT", 
"created_by": 1, 
"month_of_birth": null, 
"notes": null, 
"participant_codename": "AA3", 
"participant_id": 13, 
"participant_type": "Parent", 
"sex": "Female", 
"solved": null, 
"updated": "Wed, 18 Nov 2020 15:16:05 GMT", 
"updated_by": 1
}
```
* new participant codename …
> Flask: add POST /api/participants

- react/src/pages/addParticipants/DataEntryTable.tsx
- react/src/pages/addParticipants/utils.tsx
- react/src/pages/utils/typings.tsx
> React: Add typing for Family

- flask/app/families.py
I accidentally deleted an import that breaks POST `/api/families` in a merge for #184 
This fixes it, sorry Delvin lol
(This is why we need automated tests #165 )
> Flask: Fix broken endpoint

- react/src/pages/Navigation.tsx
- react/src/pages/analysis/Analyses.tsx
- react/src/pages/datasets/Datasets.tsx
- react/src/pages/participants/Participants.tsx
- react/src/pages/settings/Settings.tsx
Closes #201
Closes #202
Closes #203
> React: small tweaks

- flask/app/buckets.py
> Flask: remove api/objects

- react/src/pages/Navigation.tsx
- react/src/pages/analysis/Analyses.tsx
- react/src/pages/participants/ParticipantInfoDialog.tsx
- react/src/pages/participants/ParticipantTable.tsx
- react/src/pages/participants/SampleTable.tsx
- react/src/pages/utils/components/InfoList.tsx
Closes #212, excluding "Checkbox cells are misaligned with headings in participants"
> React: Navigation refactor & misc cosmetic changes

- react/src/pages/addParticipants/AddParticipants.tsx
- react/src/pages/addParticipants/DataEntryTable.tsx
- react/src/pages/addParticipants/TableCells.tsx
- react/src/pages/admin/UserDetails.tsx
- react/src/pages/utils/components/ConfirmModal.tsx
- react/src/pages/utils/functions.tsx
- react/src/pages/utils/typings.tsx
Closes #222.
The `condition` field was also changed to be required on frontend with default value `GermLine`, since it's set as not nullable.
> React: Hook up add participants submit button

- react/src/App.tsx
- react/src/pages/Login.tsx
- react/src/pages/Navigation.tsx
- react/src/pages/NotificationPopover.tsx
- react/src/pages/admin/Admin.tsx
- react/src/pages/admin/CreateUserModal.tsx
- react/src/pages/admin/UserRow.tsx
> React: dark mode

- react/src/pages/datasets/DatasetTable.tsx
- react/src/pages/participants/ParticipantTable.tsx
- react/src/pages/utils/components/DetailSection.tsx
Closes #215
Also fixes a bug where DetailSection fields can overlap the Edit Mode switch if the field is long enough.
> React: Fix 'Pipeline: undefined undefined' issue in analysis dialogs

- react/src/pages/analysis/Analyses.tsx
- react/src/pages/datasets/DatasetTable.tsx
- react/src/pages/participants/ParticipantTable.tsx
- react/src/pages/utils/functions.tsx
- react/src/pages/utils/typings.tsx
> React: CSV export button for all tables

- flask/app/analyses.py
- react/src/pages/analysis/Analyses.tsx
- react/src/pages/utils/functions.tsx
- react/src/pages/utils/typings.tsx
> Flask & React: Display pipeline name, version instead of id on analyses page

- react/src/pages/addParticipants/UploadDialog.tsx
> React: add snackbar feedback for CSV upload

- flask/app/__init__.py
- flask/app/routes.py
- flask/app/users.py
- flask/tests/test_users.py
- react/src/pages/admin/CreateUserModal.tsx
- react/src/pages/admin/UserDetails.tsx
- react/src/pages/admin/UserList.tsx
- react/src/pages/admin/UserRow.tsx
- react/src/pages/utils/components/ChipSelect.tsx
- react/src/pages/utils/typings.tsx
Now returns an array of JSON objects of the username, email, admin status, last login, activation status, and an array of group codes.
Also hook up the user list to use this updated endpoint.
#193
> Flask: update GET /api/users, move to users.py, add tests

- flask/app/users.py
- flask/tests/test_users.py
#193 
~~Waiting for rebasing the last two commits against master first after #267 merged~~
> Flask: add GET, POST /api/users/:username

- react/src/Admin/components/UserList.tsx
Fixes typecasts and makes the state transition system better typed
> React: use type disjunction in UserList reducer

- react/src/AddDatasets/components/DataEntryTable.tsx
- react/src/Settings/index.tsx
> React: link to MinIO

- flask/app/routes.py
- flask/app/users.py
- flask/tests/test_users.py
- react/src/Admin/components/UserList.tsx
> Flask: update DELETE /api/users to DELETE /api/users/:username

- README.md
- react/package.json
- react/public/index.html
- react/public/manifest.json
- react/src/AddDatasets/index.tsx
- react/src/Admin/components/UserList.tsx
- react/src/Analyses/index.tsx
- react/src/Datasets/index.tsx
- react/src/Login.tsx
- react/src/Participants/index.tsx
- react/src/Settings/index.tsx
Renaming the repository on merge
> React: rename to Stager with app name in REACT_APP_NAME envvar

- flask/app/routes.py
- flask/app/users.py
- flask/tests/test_users.py
- react/src/Admin/components/UserDetails.tsx
- react/src/Admin/components/UserList.tsx
- react/src/Settings/index.tsx
- react/src/components/NewPasswordForm.tsx
Replaces PUT /api/users and POST /api/password
Hook up to frontend
Closes #193
Closes #188
> Flask: add PATCH /api/users/:username

- flask/app/routes.py
- flask/tests/conftest.py
- flask/tests/test_analyses.py
- flask/tests/test_families.py
- flask/tests/test_groups.py
- flask/tests/test_misc.py
- flask/tests/test_participants.py
- flask/tests/test_users.py
closes #258 
to test user permissions, need to add user in to users_groups table in mysql container
e.g
` INSERT INTO users_groups VALUES(1, 3);`
and test:
```
curl -X POST \
--data '[{
"family_codename": "1001",
"participant_codename": "1411",
"tissue_sample": "Blood",
"tissue_sample_type": "Blood",
"dataset_type": "WGS",
"condition": "GermLine",
"sequencing_date": "2020-12-17"
}]' \
"localhost:3000/api/_bulk?group=ach&user=1"
```
> /api/_bulk: add group query string parameter

- react/src/AddDatasets/components/DataEntryTable.tsx
- react/src/AddDatasets/components/TableCells.tsx
- react/src/AddDatasets/components/utils.tsx
- react/src/Admin/components/UserList.tsx
- react/src/Datasets/components/AnalysisRunnerDialog.tsx
- react/src/Datasets/components/DatasetTable.tsx
- react/src/Datasets/components/LinkedFilesButton.tsx
- react/src/Datasets/components/LinkedFilesPopover.tsx
- react/src/Participants/components/SampleTable.tsx
- react/src/functions.tsx
- react/src/typings.tsx
> React: Add render component for multiple files on Datasets page

- flask/app/__init__.py
- flask/app/utils.py
- react/package.json
- react/src/Analyses/index.tsx
- react/src/Datasets/components/DatasetTable.tsx
- react/src/Participants/components/SampleTable.tsx
- react/src/components/DateTimeText.tsx
- react/src/components/index.tsx
- react/src/functions.tsx
- react/yarn.lock
> React & Flask: JSONEncoder for ISO datetimes, day.js for frontend datetimes

- react/src/Admin/components/UserRow.tsx
> React: Fix persistent italics for reactivated users

- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
#315
> CI: add CodeQL and Dependabot

- flask/app/routes.py
- flask/tests/conftest.py
- flask/tests/test_misc.py
closes #313 
```
curl localhost:5000/api/institutions
[
"Alberta Children's Hospital", 
"BC Children's Hospital", 
"Children's Hospital of Eastern Ontario", 
"CHU Ste-Justine", 
"Credit Valley Hospital", 
"Hamilton Health Sciences Centre", 
"Health Sciences North", 
"International", 
"IWK Health Centre", 
"Kingston Health Sciences Centre", 
"London Health Sciences Centre", 
"Montreal Children's Hospital", 
"Mount Sinai Hospital", 
"North York General Hospital", 
"Saskatoon Health Region", 
"Stollery Children's Hospital", 
"The Hospital for Sick Children", 
"The Ottawa Hospital", 
"University Health Network", 
"Winnipeg Regional Health", 
"Unknown"
]
```
> Flask: add GET api/institutions

- .github/workflows/flask.yml
- .github/workflows/react.yml
- react/deploy.sh
Enable dependency caching for frontend workflows. MinIO secrets (MINIO_ACCESS_KEY, MINIO_SECRET_KEY, MINIO_HOST, MINIO_BUCKET) have been added to repository secrets already.
#315
> CI: add frontend deploy step on master

- .github/workflows/flask.yml
#315 
Something did break after all 😅
> CI: build and push development image in separate steps

- flask/app/routes.py
> Flask: prevent deactivated users from signing in

- flask/app/analyses.py
- flask/app/datasets.py
- flask/app/families.py
- flask/app/participants.py
- flask/app/routes.py
closes #311
Not sure what 'See how the Analysis-User relationship and the pipeline supported type relationships are used.' in the issue description is referring to.
> Add institution field to APIs returning participants 

- react/src/AddDatasets/components/utils.tsx
- react/src/Datasets/components/DatasetInfoDialog.tsx
- react/src/Datasets/components/DatasetTable.tsx
- react/src/Participants/components/ParticipantInfoDialog.tsx
- react/src/Participants/components/ParticipantTable.tsx
- react/src/Participants/components/SampleTable.tsx
- react/src/components/AnalysisInfoDialog.tsx
- react/src/components/DetailSection.tsx
- react/src/components/FieldDisplayEditable.tsx
- react/src/components/GridFieldsDisplay.tsx
- react/src/components/InfoList.tsx
- react/src/hooks/index.tsx
- react/src/hooks/useEnumsQuery.tsx
- react/src/hooks/useMetadatasetTypesQuery.tsx
- react/src/typings.tsx
- useMemo for postprocessing of /api/enums
- add typing for enums passed down as prop
#318
> React: use /api/metadatasettypes, switch chip bar type

- react/src/Participants/components/ParticipantInfoDialog.tsx
- react/src/hooks/index.tsx
- react/src/hooks/useInstitutionsQuery.tsx
- react/src/typings.tsx
> React: Add institution field to participant info dialog

- react/src/AddDatasets/components/DataEntryTable.tsx
- react/src/AddDatasets/components/utils.tsx
- react/src/typings.tsx
> React: Add institution column to Add Datasets

- react/src/AddDatasets/index.tsx
- react/src/hooks/bulk/useBulkCreateMutation.tsx
- react/src/hooks/index.tsx
Part of #284 (POST /api/_bulk)
> React: Hookup Add Datasets using react-query

- flask/app/participants.py
- flask/app/utils.py
Part of #283
Submitting as draft PR because I'm sure it will need major revisions. Also, one test is failing (test_list_participants_admin). and I'm not sure why:
`      assert response.get_json()["total_count"] == 3
E       assert 4 == 3`
Things to consider:
Should filter queries be submitted as a json?
Should enums (e.g. sex, participant type) be validated?
Example test:
`curl "http://localhost:3000/api/participants?family_codename=2002&affected=true"`
Returns:
```
{
"data": [
{
"affected": true, 
"created": "2021-02-03T18:15:53", 
"created_by": "admin", 
"family_codename": "2002", 
"institution": "Children's Hospital of Eastern Ontario", 
"month_of_birth": null, 
"notes": null, 
"participant_aliases": null, 
"participant_codename": "CHEO0007", 
"participant_id": 7, 
"participant_type": …
```
> Flask: reduce data overfetch from participants

- flask/app/buckets.py
- react/src/AddDatasets/components/DataEntryTable.tsx
- react/src/Datasets/components/DatasetTable.tsx
- react/src/hooks/index.tsx
- react/src/hooks/unlinked/useUnlinkedFilesQuery.tsx
> React: Hookup unlinked files with react-query

- react/src/AddDatasets/index.tsx
- react/src/App.tsx
- react/src/Datasets/components/DatasetTable.tsx
- react/src/Navigation.tsx
- react/src/Settings/index.tsx
- react/src/contexts/index.tsx
- react/src/contexts/useUserContext.tsx
- react/src/hooks/users/useUsersUpdateMutation.tsx
> React: Fix current user groups not being updated in admin

- react/src/Navigation.tsx
- react/src/components/ListItemRouterLink.tsx
> React: Add tooltips to drawer links when collapsed

- react/src/Participants/components/ParticipantTable.tsx
- react/src/hooks/utils.tsx
> React: Update participants hookup for progressive loading

- react/src/AddDatasets/index.tsx
> React: Save entered Add Datasets info in sessionStorage

- Dockerfile
- docs/database.md
- docs/docker.md
- flask/Dockerfile
Add OCI metadata labels to Docker images
> docs: info about using GHCR

- flask/app/__init__.py
- flask/app/families.py
part of #361
- not sure what best practices entails but resources are welcome 
- thoughts on how verbose we want the logging
- I think we should have different handlers for sql and endpoint logging as the former can get verbose. thoughts on this and storing the logs?
- formatting TBD
Example of logging to console 
```
curl localhost:5000/api/families
app_1    | [INFO] 02/16/2021 09:27:01 PM app (list_families, line 20): Parsing query parameters..
app_1    | [INFO] 02/16/2021 09:27:01 PM app (list_families, line 27): Validating max rows..
app_1    | [INFO] 02/16/2021 09:27:01 PM app (list_families, line 35): Validating 'order_by' column..
app_1    | [INFO] 02/16/2021 09:27:01 PM app (list_families, line 40): Query parameters successfully parsed.
app_1    | [INFO] 02/16/2021 09:27:01 PM app …
```
> Flask: add formatting to logger and logging to families

- flask/app/datasets.py
- flask/app/models.py
- flask/app/participants.py
- flask/app/utils.py
- flask/tests/test_datasets.py
> Flask: implement progressive loading and filtering on /api/datasets

- react/src/Analyses/index.tsx
- react/src/Datasets/components/AnalysisRunnerDialog.tsx
- react/src/components/AnalysisInfoDialog.tsx
- react/src/components/NotificationPopover.tsx
- react/src/hooks/analyses/useAnalysesPage.tsx
- react/src/hooks/analyses/useAnalysesQuery.tsx
- react/src/hooks/analyses/useAnalysisCreateMutation.tsx
- react/src/hooks/analyses/useAnalysisDeleteMutation.tsx
- react/src/hooks/analyses/useAnalysisQuery.tsx
- react/src/hooks/analyses/useAnalysisUpdateMutation.tsx
- react/src/hooks/index.tsx
- react/src/typings.tsx
> React: Hookup analyses page with react-query

- flask/app/routes.py
part of #361
Initially had most events logged as debug but thought it might be more informative to convert a few to info to ensure things are running smoothly.
> Flask: add logging to endpoints in routes

- flask/app/tissue_samples.py
> Flask: add logging to tissue sample endpoints

- .github/workflows/flask.yml
- Dockerfile
- docker-compose.prod.yaml
- flask/app/config.py
- flask/app/models.py
- flask/app/routes.py
> Flask: embed GIT_SHA in image, add /api to retrieve

- flask/app/users.py
> Flask: logging to user endpoints

- flask/app/datasets.py
- react/src/Datasets/components/DatasetTable.tsx
- react/src/hooks/datasets/useDatasetCreateMutation.tsx
- react/src/hooks/datasets/useDatasetDeleteMutation.tsx
- react/src/hooks/datasets/useDatasetUpdateMutation.tsx
Part of #284
~~Todo before review:~~ Will solve these issues in a separate PR. Seems to be much more complicated than just assigning columns to a state variable.
~~- [ ] Fix dataset filter buttons erasing other filters.~~
~~- [ ] Fix delayed disappearing filters after new query.~~
> React: Update datasets table to use progressive loading

- flask/app/users.py
- flask/tests/test_users.py
> Flask: prevent admin from deleting self

- react/src/Admin/components/UserDetails.tsx
> React: Disable delete user button for self

- flask/app/analyses.py
- flask/app/models.py
- flask/tests/test_analyses.py
Branched from #389, to be reviewed after
Fix some N+1 bugs
Closes #283
> Flask: implement progressive loading and filtering on /api/analyses

- .github/workflows/label.yml
https://securitylab.github.com/research/github-actions-preventing-pwn-requests
https://github.com/actions/labeler#create-workflow
> CI: fix automatic labels for Dependabot and external PRs

- react/package.json
- react/src/App.tsx
View latest commit hash in browser console in production environment
> React: add REACT_APP_GIT_SHA env var to build script and print to console

- react/src/Datasets/components/DatasetTable.tsx
It seems that the MaterialTable instance in `DatasetTable.tsx` was rerendering when `api/unlinked` was fetched in the background, causing filters on the table to reset. The table was rerendering b/c some of its props were inline functions which, according to react's equivalency checks, are technically 'new' on every render. Defining these functions outside of the component seems to have fixed the issue on my tests, but confirmation is needed.
> define inline functions and components to avoid rerenders

- flask/app/manage.py
Required for the migration as of April 12.
> db: seed dig2 pipeline for RRS, add separate group seed command without dummy users

- flask/app/models.py
- flask/migrations/versions/2a2bc309568d_initial_migration.py
- flask/tests/test_misc.py
Part of #505 
Making a PR in case we want to include this in the initial migration before rollout
> Flask: add priority column to analysis table

- .github/workflows/react.yml
Secrets have been already added
> CI: build frontend for both CCM and CHEO-RI targets on master only

- flask/app/datasets.py
Fix error 500 due to accessing username of None assignees
Fix error 500 due to incorrect syntax for ordering on updated_by
Fix list endpoint returning tissue sample created_by/updated_by instead of that of the dataset
> Flask: minor bug fixes to /api/datasets

- react/src/AddDatasets/components/DataEntryTable.tsx
- react/src/AddDatasets/components/UploadCSV.tsx
- react/src/AddDatasets/components/UploadDialog.tsx
- react/src/AddDatasets/components/utils.tsx
Closes #504 
Adds a button that downloads the contents of the Data Entry Table in it's current state in .csv format.
> React: CSV template download in Add Datasets

- flask/app/analyses.py
Fixes 500 Server Error when attempting to PATCH /api/analyses/<id> with a non-blank assignee username, as mentioned in #526.
> Flask: Fix setting assignee for analysis

- react/package.json
- react/src/AddDatasets/components/utils.tsx
- react/yarn.lock
> React: display sequencing_date as Report Date

- react/src/components/GridFieldsDisplay.tsx
> React: Fix text wrapping inside info dialogs

- react/src/Settings/components/Instructions.tsx
- react/src/Settings/index.tsx
Closes #541 
Writing is hard and Prettier does not like actual markup
> React: add MinIO usage instructions to Settings

- flask/app/analyses.py
- flask/tests/test_madmin.py
> Flask: Replace pipeline_id column with analysis_state column in analyses csv export

- react/src/Analyses/index.tsx
- react/src/Datasets/components/DatasetTable.tsx
- react/src/Participants/components/ParticipantTable.tsx
- react/src/hooks/index.tsx
- react/src/hooks/useHiddenColumnCache.tsx
Last part of #550
Hidden columns are loaded similarly to #587.
> React: Save hidden column states to localStorage

- react/src/Analyses/components/PipelineFilter.tsx
- react/src/components/BooleanFilter.tsx
- react/src/components/DateFilterComponent.tsx
Custom `filterComponent` needs to be controlled by value `props.columnDef.tableData.filterValue` and update function `props.onFilterChanged` in order for #587 to work.
> React: Update custom material-table filters to be controlled components

- .github/workflows/react.yml
I forgot to include this in secrets after #566.
> CI: add REACT_APP_EMAIL to builds

- react/src/Analyses/components/PipelineFilter.tsx
> React: Fix pipeline filter not being updated properly

- flask/app/variants.py
- react/src/SearchVariants/components/Autocomplete.tsx
- react/src/SearchVariants/components/SearchVariantsPage.tsx
- react/src/hooks/genes/useGenesQuery.ts
- react/src/typings.tsx
Fix up error handling, store gene panel in localStorage
Closes #621 
Is it worth it to make the RadioGroup a controlled component?
> React: update variant viewer frontend to match #568 

- react/src/Admin/components/CreateUserModal.tsx
- react/src/Admin/components/UserDetails.tsx
- react/src/App.tsx
- react/src/contexts/index.tsx
- react/src/contexts/useOAuthContext.tsx
- react/src/typings.tsx
- Add subject, issuer fields to UserDetails (editing existing user), and CreateUserModal (adding new user)
> React: Add OAuth fields to Admin Page

- flask/app/users.py
- Update POST /api/users to support OIDC fields
- Update PATCH /api/users/:username to support OIDC fields
- Update jsonify_user to return OIDC fields if permitted
Example:
```
curl --header "Content-Type: application/json" -X POST --data '{"username":"testuser","password":"secret","email":"user@example.com","issuer":"https://accounts.google.com","subject":"123456789"}' http://localhost:5000/api/users
{
"deactivated": false, 
"email": "user@example.com", 
"groups": [], 
"is_admin": false, 
"issuer": "https://accounts.google.com", 
"last_login": null, 
"minio_access_key": "2d3a51503ce710ed", 
"minio_secret_key": "8766837f5b275d17891bc982fc4aaf8a", 
"subject": "123456789", 
"username": "testuser"
}
```
```
curl --header "Content-Type: application/json" -X PATCH --data …
```
> Flask: Update user endpoints to support OIDC fields

- flask/app/analyses.py
> Flask: Add logging to analysis endpoints

- react/src/AddDatasets/components/DataEntryTable.tsx
- react/src/Datasets/components/DatasetTable.tsx
- react/src/components/FileLinkingComponent.tsx
closes #617 
* limit autocomplete panel display of unlinked files to 25
* show selected files in tags
> React: Refactor file select input to render minimal options

- flask/app/groups.py
> Flask: Add logging to groups endpoints

- flask/app/buckets.py
> Flask: Add logging to unlinked files endpoint

- flask/app/variants.py
> Flask: add column names as a list to ensure consistent ordering

- flask/app/analyses.py
- flask/app/datasets.py
> Flask: Allow sorting by analysis_id, dataset_id

- react/src/App.tsx
> React: Prevent login page from momentarily rendering on reload

- flask/app/variants.py
- react/src/SearchVariants/components/Autocomplete.tsx
- react/src/SearchVariants/components/CardButton.tsx
- react/src/SearchVariants/components/SearchVariantsPage.tsx
~~Part of~~ Closes #654
Also fixes the filename for participant-wise reports.
Thanks to @delvinso for the descriptions.
> React: Add descriptions to variant report types

- flask/app/datasets.py
- flask/app/participants.py
- react/src/Analyses/components/PipelineFilter.tsx
- react/src/Datasets/components/DatasetTable.tsx
- react/src/Participants/components/ParticipantTable.tsx
Part of #603 
Adds filtering by permission_group for datasets, and dataset_type for participants
> Flask & React: Filter by multi-value columns

- flask/app/manage.py
refs #676 
- this click command locates analyses associated with incorrect pipelines based on related `dataset.dataset_type` and updates them to the correct value.
- the script can be run via docker with `docker exec <app-container> flask update-analysis-pipelines` or in a shell inside the app container.
- I can provide a sql query to check for misassociated pipelines via DM that can be run before and after script execution to verify results.
> Flask/DB: Click command to reassociate analyses with correct pipelines

- flask/app/users.py
- flask/tests/test_users.py
> Flask/Minio: Remove Minio group policies from admins to prevent overrides

- flask/app/manage.py
- flask/app/manage_keycloak.py
- flask/app/routes.py
- react/src/App.tsx
- react/src/Login.tsx
- react/src/Navigation.tsx
> React: Update OAuth login flow for untracked users

- docker-compose.yaml
- flask/app/manage.py
- correct the datetime import in `manage.py` as an alternate import of the datetime package was breaking the dev db seed 
- remove unused mount in `docker-compose.yaml`
> Flask/Docker: minor fixes and changes

- react/src/SearchVariants/components/SearchVariantsPage.tsx
> React: Create loading indicator for SearchVariants page

- flask/app/analyses.py
- flask/app/participants.py
> Flask: Add linked_files to participants and analysis [get] payloads

- react/src/Admin/components/UserRow.tsx
- react/src/App.tsx
- react/src/Login.tsx
- react/src/components/DetailSection.tsx
- react/src/components/ListItemRouterLink.tsx
- react/src/components/SecretDisplay.tsx
Resolved Material-UI related deprecation warnings
> React: Remove deprecated material-ui code

- docs/keycloak.md
> Docs: instructions for linking third-party IdPs to Keycloak

- flask/app/analyses.py
- Added missing fields (specifically family_aliases and participant_aliases) to `"/api/analyses/<int:id>", methods=["GET"]`
> Fixed missing fields bug

- flask/app/datasets.py
- flask/app/models.py
- flask/tests/conftest.py
- flask/tests/test_datasets.py
- flask/tests/test_misc.py
- flask/tests/test_samples.py
- react/public/index.html
- react/src/Datasets/components/DatasetTable.tsx
- react/src/components/ConfirmModal.tsx
- react/tsconfig.json
closes #797 
- Added request to backend
- Added delete functionality for the appropriate rows in `groups_datasets` and `tissue_sample` tables. 
- It seems like we're not sure whether we should delete the associated analysis yet, so I'm leaving it as is.
> Flask/ React: Fixed delete bug

- flask/app/routes.py
- flask/tests/test_misc.py
> Flask: Ignore empty lines in csvs during bulk upload

- docker-compose.test.yaml
- react/src/Datasets/components/DatasetInfoDialog.tsx
- react/src/Participants/components/ParticipantInfoDialog.tsx
- react/src/components/AnalysisInfoDialog.tsx
- react/src/components/LoadingIndicator.tsx
- react/src/components/index.tsx
For the modals (info dialog) in `Participant` `Analysis` `Dataset` tables, a backdrop and a circular progress icon are implemented. The new feature is effective when a user saves changes in the modal and when a user opens up the modal.
> React: Modal loading and circular progress icon display. 

- flask/app/buckets.py
- flask/app/config.py
- flask/app/groups.py
- flask/app/utils.py
> Flask: add MINIO_TLS envvar

- flask/app/tasks.py
- Added and removed some fields in the email template based on Madeline's feedback.
> Flask: modified fields in notification email

- .github/workflows/flask.yml
- docker-compose.ccm.yaml
Halve the number of Gunicorn workers as to divide the number of processes (ish) between tenants.
> CI: deploy Aleixo Muise lab tenant

- react/src/AddDatasets/components/UploadDialog.tsx
- react/src/AddDatasets/index.tsx
- react/src/Admin/components/CreateUserModal.tsx
- react/src/App.tsx
- react/src/Groups/index.tsx
- react/src/Login.tsx
- react/src/Navigation.tsx
- react/src/Settings/index.tsx
- react/src/hooks/analyses/useAnalysesQuery.tsx
- react/src/hooks/analyses/useAnalysisQuery.tsx
- react/src/hooks/datasets/useDatasetQueries.tsx
- react/src/hooks/datasets/useDatasetQuery.tsx
- react/src/hooks/datasets/useDatasetsQuery.tsx
- react/src/hooks/family/useFamiliesQuery.tsx
- react/src/hooks/genes/useGenesQuery.ts
- react/src/hooks/groups/useGroupsQuery.tsx
- react/src/hooks/index.tsx
- react/src/hooks/participants/useParticipantQuery.tsx
- react/src/hooks/useDownloadCsv.ts
- react/src/hooks/useInstitutionsQuery.tsx
- react/src/hooks/useMetadatasetTypesQuery.tsx
- react/src/hooks/usePipelinesQuery.tsx
- react/src/hooks/users/useUserQuery.tsx
- react/src/hooks/users/useUsersQuery.tsx
- react/src/hooks/utils.tsx
Reverts ccmbioinfo/stager#1010
Login page was unconditionally disabled.
> Revert "React: improve AJAX error handling (#1010)" 

- .github/workflows/flask.yml
- README.md
- docs/flask.md
- flask/.dockerignore
- flask/.gitignore
- flask/requirements-dev.in
- flask/requirements-dev.txt
`Pytest-cov:` https://pytest-cov.readthedocs.io/en/latest/readme.html
> CI: Use pytest-cov to measure code coverage

- flask/app/manage.py
Fixes some click commands not working because MINIO_TLS wasn't considered
> Flask: make most initializations of MinIO client SDKs consistent

- flask/app/manage.py
Reverts ccmbioinfo/stager#1027
> Revert "Flask: make most initializations of MinIO client SDKs consistent"

- Dockerfile
- flask/Dockerfile
- flask/tests/test_misc.py
- flask/tests/unit/test_json_validation_decorator.py
Reverts ccmbioinfo/stager#1028
```
Usage: python -m flask db upgrade [OPTIONS] [REVISION]
Try 'python -m flask db upgrade --help' for help.
Error: While importing 'wsgi', an ImportError was raised.
```
> Revert "Flask: upgrade to Python 3.8 "

- react/src/Analyses/index.tsx
> React: Expose button to delete analysis on the front-end

- .github/workflows/compose-validate.yml
- docker-compose.ccm.yaml
Fix bad indentation for one container in #1078 and add a check so this doesn't happen again.
> CI: add workflow to validate Docker Compose files

- .github/workflows/react.yml
> CI: use actions/setup-node to cache yarn dependencies

- react/src/components/FieldDisplayEditable.tsx
> React: Fix the bug in dataset modal to get options for Dataset types

- Dockerfile
- docker-compose.ccm.yaml
- docker-compose.cheo.yaml
- docker-compose.test.yaml
- docker-compose.yaml
- flask/Dockerfile
- flask/app/__init__.py
- flask/app/email.py
- flask/gunicorn.conf.py
> Flask: configure timezones at container level, gunicorn in gunicorn.conf.py

- flask/app/__init__.py
- flask/app/blueprints/__init__.py
- flask/app/blueprints/analyses.py
- flask/app/blueprints/datasets.py
- flask/app/blueprints/error_handler.py
- flask/app/blueprints/families.py
- flask/app/blueprints/genes.py
- flask/app/blueprints/groups.py
- flask/app/blueprints/misc.py
- flask/app/blueprints/participants.py
- flask/app/blueprints/tissue_samples.py
- flask/app/blueprints/unlinked.py
- flask/app/blueprints/users.py
- flask/app/blueprints/variants.py
- flask/tests/test_datasets.py
- flask/tests/test_misc.py
- flask/tests/test_users.py
Separated from https://github.com/ccmbioinfo/stager/pull/1150
> Flask: move blueprints to directory, routes -> misc, buckets -> unlinked

- Dockerfile
- docker-compose.oidc.yaml
- docker-compose.test.yaml
- docker-compose.yaml
- flask/Dockerfile
- flask/app/blueprints/groups.py
- flask/app/madmin.py
- flask/tests/test_groups.py
- flask/tests/test_madmin.py
Three high-severity vulnerabilities with real consequences:
- CVE-2021-43858  / GHSA-j6jc-jqqc-p6cx
- CVE-2022-24842 / GHSA-2j69-jjmg-534q
- CVE-2022-31028 / GHSA-qrpr-r3pw-f636
> Docker: bump MinIO for security
