react/src/pages/analysis/Analysis.tsx
react/src/pages/analysis/DatasetTable.tsx
react/src/pages/dashboard/AnalysisTable.tsx
react/src/pages/dashboard/SamplesTable.tsx
react/src/pages/participants/ParticipantsTable.tsx
react/src/pages/upload/FilesTable.tsx

The material-table component provides built-in per-column filtering options. This change nullifies the need for a general search bar, so it is also disabled.

Per-column table filtering 

---

flask/app/models.py
flask/app/routes.py

Use dataclasses and string enums in SQLAlchemy models to automatically serialize with flask.jsonify
Add generic mixin function for PATCH use case and verify enums due to cryptic SQLAlchemy exception messages
Supersedes and closes #24

Flask: add PATCH /api/participants/<id>

---

flask/app/routes.py

A lot of the code was reused between the different PATCH endpoints so I thought it would be better to have one generic view. I'm open to splitting this into individual routes for each table though.

Flask: PATCH /api/participants/:id, /api/datasets/:id, /api/analyses/:id in one function

---

react/src/pages/analysis/Analysis.tsx
react/src/pages/dashboard/AnalysisTable.tsx
react/src/pages/dashboard/SampleTable.tsx
react/src/pages/datasets/DatasetTable.tsx
react/src/pages/upload/FilesTable.tsx
react/src/pages/utils.tsx

* Change rendering of datetime strings to ISO format (closes #82)
* Add editable cells to Analysis table (closes #79) (note: changes are local; mutations are on different branch)
* Enable dense padding for dataset, dashboard, analysis tables

ISO Date formatting (#82) and editable cells (#79)

---

react/src/pages/analysis/Analysis.tsx
react/src/pages/utils.tsx

For #80, however we may need a new PATCH endpoint for patching multiple analyses in one request (for set assignee, start analysis, cancel analysis). Only option as of now is to send 1 PATCH request for every row selected, which isn't great.

React: hook up analysis table rows, set assignee

---

flask/app/routes.py

closes #136
@kevinlul Did we want other fields, such as participant codename, family codename, etc?

GET /api/tissue_samples/:id

---

react/src/pages/participants/ParticipantTable.tsx

Instead of being set to `[]`, `dataset_types` would be undefined

React: fix rendering failure when there are no datasets for a participant or tissue sample

---

flask/app/participants.py

For `order_by()`, we need to add a default field, the alternative is to have an if else statement checking for the existence of the order query parameter and having one query with the order_by method, and one without. AFAIK there is no 'default' parameter we can pass into order_by to get the default sql ordering scheme (if there is we can just assign that as default and pass it into order_by) 
No user groups exist for testing permissions so we need to exec into the MySQL container and `insert into users_groups values (1,1); insert into groups_datasets values (1,1);` (thanks to Samarth)
some examples:
```
curl  "localhost:5000/api/participants?max_rows=1&starts_with=AA&order=sex" 
curl "localhost:5000/api/participants?max_rows=1&starts_with=AA&order=sex&user=1
curl …
```

Flask: add query parameters to GET api/participants

---

react/src/pages/analysis/Analyses.tsx
react/src/pages/datasets/DatasetTable.tsx
react/src/pages/participants/ParticipantTable.tsx
react/src/pages/utils/components/Note.tsx

Closes #231 
The component handles overflowing text in `notes` columns, and expands on mouse hover to show the entire entry.

React: Fix notes changing table row height

---

flask/app/__init__.py
flask/app/analyses.py
flask/app/config.py
flask/app/datasets.py
flask/app/families.py
flask/app/participants.py
flask/app/routes.py
flask/tests/badsamplecsv.csv
flask/tests/conftest.py
flask/tests/samplecsv.csv
flask/tests/test_analyses.py
flask/tests/test_datasets.py
flask/tests/test_families.py
flask/tests/test_login.py
flask/tests/test_misc.py
flask/tests/test_participants.py
flask/tests/test_samples.py

Implement check_admin decorator
Add Config.SQLALCHEMY_LOG to disable SQL query logs in unit tests
Closes #165

Flask: add unit tests for all endpoints

---

Dockerfile
docker-compose.prod.yaml
docker-compose.test.yaml
docker-compose.yaml
nginx/conf.d/default.conf

nginx: [forward MinIO](https://docs.min.io/docs/setup-nginx-proxy-with-minio.html) on port 9000 again
nginx: fix public certificate path to use bundle with full certificate chain
compose: use latest version 3.8
compose: use correct prod app Dockerfile and fix CMD syntax

nginx: forward MinIO on port 9000, other production fixes

---

flask/tests/conftest.py

closes #250 
The way Flask intended for tests to be written via pytest is with 1 request per function, and the test_client as a fixture with scope function. I think that is way to verbose and don't want to go back and change that, so I set the test_client to function scope which will stop app context errors across functions (because that would be next to impossible to debug).
I say we just ignore that the requests within one function share the same context and keep the possible error in mind, thoughts @kevinlul ?

Test Scoping

---

flask/app/__init__.py
flask/app/groups.py
flask/tests/conftest.py
flask/tests/test_groups.py

closes #192 
Sample tests, will not work as expected unless User.minio_access_key and User.minio_secret_key are manually set to a manually created minio user:
```
curl -D - -X POST \
-H "Content-Type: application/json" \
--data '{"group_name" : "bruh20", "group_code" : "whoknows20",
"users": [
"admin"
]
}' \
localhost:5000/api/groups
curl -D - -X PATCH \
-H "Content-Type: application/json" \
--data '{"group_name" : "changed20.1",
"users": [
]
}' \
localhost:5000/api/groups/whoknows20
curl -D - -X DELETE \
localhost:5000/api/groups/whoknows20
```

Flask: Groups endpoints

---

react/src/pages/datasets/DatasetInfoDialog.tsx
react/src/pages/participants/ParticipantInfoDialog.tsx
react/src/pages/participants/SampleTable.tsx
react/src/pages/utils/components/AnalysisInfoDialog.tsx
react/src/pages/utils/components/DetailSection.tsx
react/src/pages/utils/components/FieldDisplay.tsx
react/src/pages/utils/components/FieldDisplayEditable.tsx
react/src/pages/utils/components/GridFieldsDisplay.tsx
react/src/pages/utils/components/InfoList.tsx
react/src/pages/utils/functions.tsx

- Components associated with `DetailSection` are now separated into different files and broken down further.
- `GridFieldsDisplay` moved to separate file.
- editable `TextField` overwrite in `DetailSection` moved to file with `FieldDisplayEditable`.
- `FieldDisplay` moved to separate file.
- Above components updated to take `enums` as props, as opposed to fetching enums for each element that needs them. May be worth looking into making a custom "useEnums" hook in the future.
- State management should be more clear now 
- Dialog holds the state of the selected 'record' (dataset, analysis, etc.).
- Child elements are passed props with this state and a way to update it. 
- `DetailSection` uses state to track edit mode changes that may be discarded.

React: Detail Dialog refactor

---

flask/app/config.py
flask/app/routes.py
flask/app/users.py
flask/tests/conftest.py
flask/tests/test_users.py
react/src/Admin/components/CreateUserModal.tsx
react/src/Admin/components/UserList.tsx

Now accepts admin status and groups, creates a MinIO identity, and return response more closely conforms with REST expectations.
Add conflicting checks for already-used usernames, emails. (Basic idea for #219)
Add defensive checks for blank usernames, emails, passwords.
Move password matching to frontend.
Refactor frontend user creation error handling, use wait cursor on submit, prevent multiple submission and submitting before finishing filling out the form
Use success variant snackbar.
#193

Flask & React: update POST /api/users, user creation form

---

flask/app/datasets.py
flask/app/routes.py
flask/tests/samplecsv.csv
flask/tests/test_datasets.py
flask/tests/test_misc.py
react/src/AddDatasets/components/DataEntryTable.tsx

closes #223
```
curl -X POST \
--data '{
"tissue_sample_id": "1",
"dataset_type": "CES",
"input_hpf_path": "/hpf/CES",
"notes": "blahblah",
"condition": "GermLine",
"extraction_protocol": "Something",
"capture_kit": "capture kit x",
"read_length": "150",
"read_type": "PairedEnd",
"discriminator": "dataset",
"sequencing_date": "2020-12-04"
}' \
localhost:3000/api/datasets
```

Require sequencing_date at the API level but not the database level

---

flask/app/routes.py
react/src/App.tsx
react/src/Datasets/components/DatasetTable.tsx
react/src/Datasets/index.tsx
react/src/Login.tsx
react/src/Navigation.tsx

Closes #216 
No admin page option if you're not logged in as an admin. Trying to access /admin route and other invalid routes redirects to /participants. The dataset delete button is hidden if not admin.
You can change the default admin's permissions by doing the following to the default database: 
```
docker exec -it st2020_mysql_1 /bin/bash
mysql -u $MYSQL_USER -p $MYSQL_DATABASE
insert into users_groups values (1,1); insert into groups_datasets values (1,1);
update user set is_admin=(not is_admin) where user_id=1;
```
Then refresh frontend
Take a good look, I probably missed something

React: Hide admin pages and dataset delete

---

flask/app/__init__.py
flask/app/analyses.py
flask/app/buckets.py
flask/app/datasets.py
flask/app/extensions.py
flask/app/families.py
flask/app/groups.py
flask/app/manage.py
flask/app/participants.py
flask/app/routes.py
flask/app/tissue_samples.py
flask/app/users.py
flask/app/utils.py

closes #221
- separating extensions from `__init__.py` into `extensions.py`
- as part of removing circular imports (imports from .extensions as opposed to import from app), logging and cli commands are also registered to the flask application through `__init__.py`
- blueprint refactor and registering
- extract shared helpers into `utils.py`

Flask: blueprints re-factor, extract helpers and separate extensions

---

Dockerfile
docker-compose.prod.yaml
docker-compose.yaml
flask/Dockerfile
flask/app/manage.py
react/.gitignore

Other:
- ignore .eslintcache
- Docker: prevent accidentally running prod images in dev and vice versa
- Compose: restart prod containers on failure, not dev

Flask: initialize MinIO policies for groups in dummy data

---

react/src/AddDatasets/components/DataEntryTable.tsx
react/src/Admin/components/CreateUserModal.tsx
react/src/Admin/components/UserList.tsx
react/src/Admin/components/UserRow.tsx
react/src/App.tsx
react/src/Datasets/components/DatasetInfoDialog.tsx
react/src/Datasets/components/DatasetTable.tsx
react/src/Participants/components/ParticipantInfoDialog.tsx
react/src/Participants/components/ParticipantTable.tsx
react/src/components/AnalysisInfoDialog.tsx
react/src/contexts/EnumContext.tsx
react/src/contexts/EnumProvider.tsx
react/src/contexts/fetchCache/FetchCacheContext.tsx
react/src/contexts/fetchCache/FetchCacheProvider.tsx
react/src/contexts/fetchCache/index.tsx
react/src/contexts/fetchCache/useFetchCache.tsx
react/src/contexts/useEnums.tsx

Closes #277. 
API calls made through `useFetchCache` are only fetched once, and taken from cache for every subsequent call. This may cause issues later for calls like `/api/groups` which can be updated during a session, so we should revisit this later and use a library like react-query to save the hassle of setting up refetch policies from scratch.

React: useFetchCache hook for caching any api call for session duration

---

react/src/Analyses/index.tsx
react/src/Datasets/components/DatasetTable.tsx

Quick fix for this weird behaviour. 
There is still a bug where the page re-renders when you open/close the Drawer, or when you click the dark mode switch on the AppBar. My guess is it's related to how the routes are rendered or something, but I haven't figured it out.

React: Fix material-table filters being deleted upon first typing

---

flask/app/groups.py

I don't think the frontend is handling the 204 even though it receives the response when I look in the Network tab...

Flask: fix empty group deletion returning 422 on success

---

react/src/AddDatasets/components/DataEntryTable.tsx
react/src/AddDatasets/components/TableCells.tsx
react/src/AddDatasets/components/utils.tsx
react/src/AddDatasets/index.tsx
react/src/functions.tsx

I was not able to reproduce the bug, but seeing as calling `.trim(...)` requires the string to be defined, I replaced it with a helper function that checks if undefined and tests the string using `RegEx.test`.

React: Fix empty string check in Add Datasets

---

react/src/AddDatasets/index.tsx

Closes #310 
- Users in only one group will be automatically filled in
- Users in multiple groups will start with no group selected to prevent mistakes

React: Fix permission group dropdown defaults in Add Datasets

---

flask/app/routes.py
flask/tests/conftest.py
flask/tests/test_misc.py

closes #317
curl localhost:5000/api/metadatasettypes 
```
{
"Exome": [
"CES", 
"CPS", 
"RCS", 
"RDC", 
"RDE", 
"RES", 
"WES"
], 
"Genome": [
"CGS", 
"RGS", 
"WGS"
], 
"Other": [
"RLM", 
"RMM", 
"RTA"
], 
"RNA": [
"RRS"
]
}
```

Flask: add GET /api/metadatasettypes

---

react/src/AddDatasets/components/DataEntryTable.tsx
react/src/App.tsx
react/src/Groups/components/CreateGroupModal.tsx
react/src/Groups/components/Group.tsx
react/src/Groups/index.tsx
react/src/hooks/groups/useGroup.tsx
react/src/hooks/groups/useGroups.tsx
react/src/hooks/groups/useGroupsDelete.tsx
react/src/hooks/groups/useGroupsPatch.tsx
react/src/hooks/groups/useGroupsPost.tsx
react/src/hooks/index.tsx
react/src/hooks/useEnums.tsx
react/src/hooks/useFamilies.tsx
react/src/hooks/useGroups.tsx

These custom hooks each correspond to the 'groups' endpoints, and help for managing fetching behaviour in one place.

React: Refactor /api/groups hookup to use react-query

---

flask/app/groups.py
flask/app/madmin.py
flask/app/manage.py
flask/tests/test_groups.py
flask/tests/test_users.py

Closes #314
This doesn't prevent overwriting the object with a blank file because that's the same permission in S3. At most we could enable [object versioning](https://stackoverflow.com/questions/10592541/amazon-s3-acl-for-read-only-and-write-once-access on the [instance](https://docs.minio.io/docs/minio-bucket-versioning-guide.html). We should revisit the subject with our collaborators.
To test this, you probably need to reset your db and local minio so it can recreate the policies correctly and not make assumptions based on the current state.

Flask: deny MinIO delete actions

---

flask/app/analyses.py

closes #307 
To test:
Start (Running)
```
curl -X PATCH \
--data '{
"notes": "hello",
"analysis_state": "Running"
}' \
localhost:5000/api/analyses/1
{
"analysis_id": 1, 
"analysis_state": "Running", 
"assignee": "admin", 
"finished": "2021-02-01T20:08:49", 
"notes": "hello", 
"pipeline_id": 1, 
"qsub_id": null, 
"requested": "2021-02-01T00:00:00", 
"requester": "admin", 
"result_path": null, 
"started": "2021-02-01T20:09:04", 
"updated": "2021-02-01T20:09:04", 
"updated_by_id": "admin"
}
```
End (Done)
```
curl -X PATCH \
--data '{
"notes": "hello",
"analysis_state": "Done"
}' \
localhost:5000/api/analyses/1
{
"analysis_id": 1, 
"analysis_state": "Done", 
"assignee": "admin", 
"finished": "2021-02-01T20:09:19", …
```

Flask: update start and finish times based on analysis state changes

---

react/src/hooks/groups/useGroupCreateMutation.tsx
react/src/hooks/groups/useGroupDeleteMutation.tsx
react/src/hooks/groups/useGroupUpdateMutation.tsx
react/src/hooks/utils.tsx

Invalidating queries with option `{ exact: true }` ensures that only queries that exactly match the given key will be invalidated, instead of all queries that contain it. The group create, update, delete hooks now use this option so that only the /api/groups query is invalidated, and not other /api/groups/:id queries that aren't affected by the action.

React: Fix groups mutations to only update group list

---

.github/workflows/flask.yml
Dockerfile
docker-compose.prod.yaml
docker-compose.test.yaml
docker-compose.yaml
flask/Dockerfile

minio/minio#11544
Should unblock all backend PRs

Docker: lock MinIO to previous version to fix CI failures

---

flask/app/manage.py
flask/app/models.py
flask/app/participants.py
flask/app/utils.py

Update default data to provide multiple children in one-to-many relationships to help test .count() behaviour.
Fix a severe N+1 type problem in this endpoint and potential security problems with user input feeding into `getattr`
#283

Flask: finish implementing progressive loading and filtering on /api/participants

---

react/src/Analyses/components/PipelineFilter.tsx
react/src/Analyses/index.tsx
react/src/components/NotificationPopover.tsx
react/src/hooks/analyses/useAnalysesPage.tsx
react/src/hooks/analyses/useAnalysesQuery.tsx
react/src/hooks/index.tsx

Related to #406
Also fixes an issue with useAnalysesQuery, and updates the notification popover to use `updated=after,{date}` parameter format.
EDIT: Added analysis_id filter changes here because front-end on `master` is broken, so this branch is easier to test on.

React: Add pipeline filter for analyses page

---

.github/workflows/flask.yml

ghcr.io/ccmbioinfo/stager is now public
Works around dependabot/dependabot-core#3253

CI: only login to registry on push workflows

---

react/src/App.tsx
react/src/hooks/utils.tsx

Remove queries from client on logout, preserving constants like enums.

clear non-static query cache on logout

---

react/src/Datasets/components/DatasetTable.tsx

Changing `defaultFilter` prop on column config causes a rerender of dataset table, wiping out filters that are already set. By using a ref to get the table instance, we can make the filter change imperatively and then force a state change by calling `onQueryChange`.

use tableRef to update dataset type filter on dataset page

---

flask/requirements-dev.txt
flask/requirements.txt

pymysql[rsa] 1.0.2 is required for the database seed to work correctly. The rest seems to be a shortcoming of dependabot, maybe related to dependabot/dependabot-core#3447. If this continues to be an issue we can create a workflow to do this on a sprint cycle for pip and yarn instead.

Flask: pip-compile --upgrade

---

flask/app/__init__.py
flask/app/gene_viewer.py

closes #481 
couple things to note
- pagination has not been implemented yet to keep review simple 
- tests are WIP
- the select statement from the query generates duplicate columns as a result of the eager joining, i subset the dataframe columns using a list, if someone knows of a more elegant solution through the orm please let me know
- for each variant, an array of participant codenames and genotypic information is also returned
- i’ve compared the output of the csv in this endpoint with one created directly from the reports and they are identical across all fields
- example json output from the example GET request above (if this should not be public let me know and I can paste in the dev chat instead)
```
curl  -i -H "Accept: application/json" …
```

Flask: add GET variant summary endpoint

---

flask/app/groups.py
flask/tests/test_groups.py

There is no XSS risk as responses are JSON, but the location header was not escaped (not a problem specifically for group code as it has to be a valid domain name).
- Add type hints and docstrings to all endpoints
- Change group not found error code, regardless of authorization, to 404
- Validate the typing of the users array for the create and update endpoints
- Update a query's syntax for SQLAlchemy 1.4
- Escape the group code in the location header anyway
- Log some exceptions

Flask: /api/groups fix-up related to CodeQL warning

---

flask/app/groups.py
flask/app/users.py
flask/app/utils.py
flask/tests/test_users.py

There is no XSS risk as responses are JSON, but the location header was not escaped, and usernames may contain arbitrary characters. This fixes that so the resulting location header is always usable, and also addresses usernames with slashes.
- Add type hints and docstrings to all endpoints
- Refactor: move get_minio_admin to utils
- Log some exceptions
- Add a simple assertion for request body typing
- Fix create_user not returning the Location header for the actual conflicting user

Flask: /api/users fix-up related to CodeQL warning

---

react/src/SearchVariants/components/Autocomplete.tsx
react/src/SearchVariants/components/SearchVariantsPage.tsx
react/src/hooks/utils.tsx
react/src/hooks/variants/useVariantsQuery.ts

* Connect variant/csv endpoint to front-end variant viewer
* return csv and automatically download when user selects gene from autocomplete list
* cache csv as blob/filename in browser via react-query
* handle 400 errors if no variants returned for selected gene

connect autocomplete to variant csv endpoint

---

flask/app/analyses.py
flask/app/utils.py
flask/tests/test_analyses.py
react/src/Analyses/index.tsx
react/src/Datasets/components/AnalysisRunnerDialog.tsx
react/src/hooks/analyses/useAnalysisCreateMutation.tsx
react/src/hooks/analyses/useAnalysisUpdateMutation.tsx
react/src/typings.tsx

close #505 
* Allow users to specify priority in run analysis modal
* Highlight rows in analysis table with Clinical or Research priority
* Filter by priority in analysis table
* Validate priority value in patch/post routes and add priority filter to index route
* Update tests

Add analysis priority flag to fe components and process attribute in backend routes

---

flask/app/datasets.py
flask/app/families.py
flask/app/groups.py
flask/app/participants.py
flask/app/routes.py
flask/app/tissue_samples.py
flask/app/users.py

GET /api
GET, POST /api/users
GET, POST /api/groups
GET, POST /api/families
GET, POST /api/participants
POST /api/tissue_samples
GET, POST /api/datasets
e.g. you can now GET `/api/` instead of just `/api` and getting a 404 on `/api/`

Flask: accept trailing slashes for endpoints with children

---

.github/workflows/flask.yml

https://docs.github.com/en/packages/guides/using-github-packages-with-github-actions#authenticating-to-github-container-registry GITHUB_TOKEN now supported over PATs, access permitted here https://github.com/orgs/ccmbioinfo/packages/container/stager/settings/actions_access

CI: login to registry with GITHUB_TOKEN

---

.github/workflows/react.yml

Apparently, hashFiles is relative to GITHUB_WORKSPACE, not the working directory
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#hashfiles
I'm surprised this didn't come up earlier

CI: fix stale yarn caches from always using the same key

---

react/src/Analyses/components/CancelAnalysisDialog.tsx
react/src/Analyses/components/SelectPipelineStatus.tsx
react/src/Analyses/components/SetAssigneeDialog.tsx
react/src/Analyses/index.tsx
react/src/App.tsx
react/src/components/SelectFilterComponent.tsx
react/src/components/index.tsx
react/src/functions.tsx
react/src/hooks/analyses/useAnalysisCreateMutation.tsx
react/src/hooks/analyses/useAnalysisDeleteMutation.tsx
react/src/hooks/analyses/useAnalysisUpdateMutation.tsx
react/src/hooks/utils.tsx

Also adds a filter component for filtering by status, and fixed query invalidation for analyses after mutations.
Known bug: 500 server error when updating analysis.assignee with valid, non-blank username; `'int' object has no attribute '_sa_instance_state'`. Seems to be related to line 421 in `analyses.py`. Blank usernames (removing assignee) works as expected. Fixed in #536.
Row-edits send all editable fields on update so due to the above backend bug, editing status can be tested by first setting the assignee field to be blank.

React: Add row-based editing for assignee, status on Analysis table

---

react/src/Analyses/index.tsx
react/src/Datasets/components/DatasetTable.tsx
react/src/Participants/components/ParticipantTable.tsx
react/src/components/MaterialTablePrimary.tsx

`width` isn't correctly applied so I removed it.
Enable the material-table column hiding feature.
Material-table also has a resizable columns feature but it's not really reliable. Using the re-resizable component would seemingly require reimplementing MTableHeader as the individual cell is just another table cell.
Remove redundant chip buttons on analysis table.

React: small tweaks to column order, remove analysis chip buttons

---

react/src/AddDatasets/components/DataEntryTable.tsx
react/src/AddDatasets/components/DataEntryTableRow.tsx
react/src/AddDatasets/components/DataEntryToolbar.tsx
react/src/AddDatasets/components/TableCells.tsx
react/src/hooks/useFamiliesQuery.tsx

Families are fetched on a per-row basis depending on that row's `family_codename` field, as opposed to being fetched once at table level.
TODO: ~~Fetch families based on `inputValue` (what the user types in the Autocomplete box) as opposed to `row.family_codename` (what the user selects from the Autocomplete selection box).~~ Finished. May require some form of debounce function to prevent fetching on every keystroke.
Functionality for Add Datasets should appear identical to master. Only difference should be in how families are fetched.

React: Add progressive loading to Add Datasets suggestions

---

flask/app/datasets.py
react/src/Analyses/index.tsx
react/src/Participants/components/ParticipantInfoDialog.tsx
react/src/Participants/components/SampleTable.tsx
react/src/components/DateTimeText.tsx
react/src/components/DetailSection.tsx
react/src/components/FieldDisplayEditable.tsx
react/src/components/GridFieldsDisplay.tsx
react/src/functions.tsx
react/src/typings.tsx

- add link to datasets table in participant info dialog
* includes adding dataset_id filter to datasets endpoint 
- update datetimetext component to return empty string when date is invalid (e.g., `null`)
- allow for variable column count in detail section to reduce vertical space
- add fullwidth option to `Field` component
- hide analyses in participant dialogue by default and toggle with button
- remove unnecessary primary keys from participant info dialogue

React: Update participant info dialog content and formatting

---

react/src/Analyses/index.tsx
react/src/Datasets/components/DatasetTable.tsx
react/src/Participants/components/ParticipantTable.tsx
react/src/hooks/index.tsx
react/src/hooks/useTableFilterCache.tsx

Part of #550 
Sets default filters by setting defaultFilter values for columns before they are added to material-table, as opposed to injecting them into the table via ref as a side effect.

React: Save default table filters to localStorage

---

nginx/conf.d/default.conf

This has proved effective on https://stager-dev.ccm.sickkids.ca for weeks now.

Docker: fix nginx resolving to stale DNS entries when containers are replaced

---

flask/app/datasets.py
react/src/Datasets/components/DatasetTable.tsx
react/src/Participants/components/ParticipantTable.tsx
react/src/components/ChipGroup.tsx
react/src/typings.tsx

Closes #546.
- Datasets returned by GET /api/datasets each include an array of group_codes associated to each dataset if applicable (if current user is admin or belongs to multiple groups).
- Frontend adds column to DatasetTable for group_code iff the current user is an admin or belongs to multiple groups.
- Update frontend typing for Dataset to include group_code

React & Flask: Add permission group column to datasets

---

flask/app/utils.py
flask/requirements-dev.txt
flask/requirements.in
flask/requirements.txt

- 'attachment_filename' parameter has been renamed to 'download_name' 
- https://palletsprojects.com/blog/flask-2-0-released/
- https://click.palletsprojects.com/en/8.0.x/changes/#version-8-0
- affected: flask and transitive dependencies like werkzeug; click from 7.1.2 to 8.0.1
- supersedes #593, #594, #612, #614

Flask: bump from 1.1.2 to 2.0.1, drop unused flask_wtf

---

flask/app/variants.py
flask/tests/test_variants.py

closes #653 
- merged participant and variant endpoints into one endpoint since both now use the same query
- description below, from endpoint docstrings
```
The same sqlalchemy query is used for both endpoints as the participant-wise report is the precursor to the variant-wise report.
The JSON response for participants is de-normalized such that each object is a participant and a variant,
whereas for the variant JSON response, each object is a variant, the annotations, and an array of genotypes for the involved participants.
Similarly, the csv output for the participants is de-normalized such that each row is a participant's variant. If the requested genes span similar coordinates duplicated variants will be returned, for each gene.
The variant csv output is a summary - each row is a …
```

Flask: changes, re-factoring endpoints for adding requested gene(s) to JSON and CSV

---

react/src/SearchVariants/components/SearchVariantsPage.tsx

Depending on screen width, cards on variant search screen might fall of out of vertical alignment if they aren't flex containers.

React: Align variant cards vertically

---

flask/app/variants.py
flask/migrations/versions/184f5edd4719_add_index_to_gene_alias_ensembl_id.py

Closes #686 
- Contains a migration for adding an index to alias table. It shares a `head` with other migrations in this sprint, so a rollback might be necessary when switching branches.

Flask: Add gene alias column to export

---

flask/app/error_handler.py

closes #709 
- prints stack trace to logs through the flask app, only if they are in the 500s

Flask: add traceback to error handler

---

flask/app/buckets.py
flask/app/datasets.py
flask/app/models.py
flask/app/routes.py
flask/app/utils.py
flask/migrations/versions/6f448fc94a2d_many_to_many_dataset_files.py
flask/tests/test_datasets.py
flask/tests/test_misc.py
react/src/AddDatasets/components/DataEntryTable.tsx
react/src/AddDatasets/components/DataEntryTableRow.tsx
react/src/AddDatasets/components/TableCells.tsx
react/src/AddDatasets/components/utils.tsx
react/src/Datasets/components/DatasetTable.tsx
react/src/Participants/components/SampleTable.tsx
react/src/components/DateFilterComponent.tsx
react/src/components/FileLinkingComponent.tsx
react/src/components/Note.tsx
react/src/components/SecretDisplay.tsx
react/src/functions.tsx
react/src/hooks/unlinked/useUnlinkedFilesQuery.tsx
react/src/typings.tsx

Closes #684 
Allow files marked `multiplexed` to be associated with multiple datasets
* migration to create new `file` table and linking table
* migration does not drop old table (for now), so switching between branches should be ok
* however... it seems we have a few migrations in this sprint, so beware that the 'head' id stored in the `alembic_versions` table might become incomprehensible to  the CLI if it refers to a migration in another branch.
* update ORM mappings to use new relationships
* update `_bulk` and `[PATCH] datasets` endpoint validation, insert, and delete logic
* update/add tests
* update unlinked files endpoint to return files as JSON (pseudo file models, basically)
* update FE file linking component and dependencies to use new file model
* add toggle feature to …

React/Flask: Add support for multiplex files

---

flask/app/models.py
flask/migrations/versions/45ed820bb437_add_variant_position_index.py

Closes #751 
Also adds an index to GeneAlias.ensembl_id in `models.py`, which was leftover from #700

Flask/Database: Add index to Variant.position

---

flask/app/models.py
flask/migrations/versions/6f448fc94a2d_many_to_many_dataset_files.py
flask/migrations/versions/b7e6ad115b13_drop_old_dataset_file_table.py

closes #753
- drops `dataset_file`, which was replaced w/ `file` and `datasets_files`
- fixup dangling mismatches b/w `models.py` and schema to prevent unnecessary diffs in autogenerated migrations
- still a lingering issue with `genotype.analysis_id_2` index

Flask/DB: Drop deprecated dataset_file table and update models

---

react/src/functions.tsx

The equality-check used by material-table [here](https://github.com/material-table-core/core/blob/master/src/material-table.js#L214) calls the `valueOf` method on object arguments, but this method does not exist on objects created with a `null` prototype.  This causes occasional errors when the table is rendered before the lookup enums are loaded (can be reproduced by refreshing the analysis page if the network is slow enough that the table renders before enums return). Removing all implementations to prevent issues in the future. [More details from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#custom_and_null_objects).

React: ensure default objects have a prototype

---

flask/app/datasets.py
flask/app/participants.py
flask/app/utils.py
flask/tests/conftest.py
flask/tests/test_analyses.py
flask/tests/test_datasets.py
flask/tests/test_families.py
flask/tests/test_participants.py

closes #804
example : `curl 'localhost:5000/api/datasets?user=1&family_codename=200&family_codename_exact_match=True'`
- Family codenames for the test database have also been changed from 'A' and 'B' to 'Aa' and 'Bb' respectively so the `*_exact_match` query parameter can be tested

Flask: add query params to perform exact search by codename in GET datasets/participants

---

flask/app/datasets.py
flask/tests/conftest.py
flask/tests/test_datasets.py
react/src/Datasets/components/DatasetTable.tsx

Added a column `sequencing_id` to the dataset table. The column can be sorted and filtered. Added test cases in test_datasets.py. Added field `sequencing_id` to the global test cases in conftest.py. 
Comment: Currently, only 4 datasets for pytest are documented in flask.md, should we update flask.md? There are 5 datasets in conftest.py.

React/Flask: Added sequencing ID field in Dataset table

---

flask/app/analyses.py
react/src/Analyses/components/AnalysisNotes.tsx
react/src/Analyses/index.tsx

- There was no way to see notes from other tabs (such as Participants or Datasets) on the Analysis page. 
- I added an Info icon in the `actions` property of the table and attached a popover that displays the notes (if there are any). 
- Modified the `get_analyses` code in `analyses.py` to also return notes from the participants tab.

React: Added aggregate notes popover on Analysis page

---

react/src/Datasets/components/DatasetTable.tsx
react/src/Participants/components/ParticipantTable.tsx
react/src/components/DetailSection.tsx
react/src/components/ExactMatchFilterToggle.tsx
react/src/components/index.tsx
react/src/functions.tsx
react/src/hooks/datasets/useDatasetsPage.tsx
react/src/hooks/utils.tsx
react/src/typings.tsx

- material-table stores an internal query object in its state (source code [here](https://github.com/mbrn/material-table/blob/42d966eacdbe47cd176f9c5c68e3d97b126b489e/src/material-table.js#L28)). This query object is internally updated by material-table whenever table properties are changed, such as when the user is filtering. 
- The approach I took was to add an additional property to this query object called `searchType` to programmatically enable exact match search when user toggles a switch. When the state of the switch changes, `onQueryChange()` is called on the table ref to requery.

React: Exact search toggle for family and participant codenames

---

.github/workflows/react.yml

I specifically added a branch protection rule to this branch to allow the deployment. When merged, we will need to change production to reverse proxy the new buckets and remove the old secrets and accounts.
For #835

CI: rewrite frontend workflow to use separate environments for security

---

flask/app/buckets.py
flask/app/datasets.py
flask/app/models.py
flask/app/routes.py
flask/migrations/versions/83abd5d883b6_add_vcf_available_and_candidate_genes_.py
flask/tests/test_misc.py
react/src/AddDatasets/components/DataEntryTable.tsx
react/src/AddDatasets/components/DataEntryTableRow.tsx
react/src/AddDatasets/components/DataEntryToolbar.tsx
react/src/AddDatasets/components/TableCells.tsx
react/src/AddDatasets/components/utils.tsx
react/src/AddDatasets/index.tsx
react/src/Analyses/components/AnalysisNotes.tsx
react/src/Datasets/components/AnalysisRunnerDialog.tsx
react/src/Datasets/components/DatasetTable.tsx
react/src/SearchVariants/components/GeneAutocomplete.tsx
react/src/SearchVariants/components/SearchVariantsPage.tsx
react/src/components/AutocompleteMultiselect.tsx
react/src/components/FileLinkingComponent.tsx
react/src/components/Note.tsx
react/src/components/index.tsx
react/src/functions.tsx
react/src/hooks/bulk/useBulkCreateMutation.tsx
react/src/hooks/genes/useGenesQuery.ts
react/src/typings.tsx

closes #796
- refactor AddDataset FE components
- lift column state management functionality to top-level component
- allow for mixed RNA/DNA seq entries on the input table
- create candidate gene lookup control
- remove unused code
- update datasets table and relevant modals to show RNAseq data
- add new RNAseq columns to DB and update name of RNAseq pipeline in migration
- update endpoints to handle RNAseq and mixed input and filter fields
- update tests

React/Flask: Add RNAseq fields to dataset entry flow

---

flask/app/datasets.py
react/src/components/DetailSection.tsx
react/src/components/FieldDisplayEditable.tsx
react/src/functions.tsx
react/src/typings.tsx

Subtask 4: For the following fields, when the limit is hit, the user cannot type into the field anymore. Sequencing Center (string max len 100) 
Batch ID (string max len 50) 
Extraction Protocol (string max len 100) 
Capture Kit (string max len 50) 
Library Prep Method (string max len 50) 
Read length (string max len 10, length of the maximum integer)
( Notes (TEXT object, do not have a length limit).) 
Subtask 5: Implement type validation for `read_length` only, `read_length` must only contain digits, as other fields are either objects or can be alphanumeric. My only concern is if making the type validation in `onChange()` would slow down the rendering. I hypothesize that this is not an issue because `error` and `helperText` are props for TextField in Material UI, so they should be …

React/Flask: Fix datasets editing modal (#814)

---

flask/app/analyses.py
flask/app/routes.py

closes #846 and #847 
I didn't think it was necessary to update tests, but as a sanity check for both:
- GET analyses (csv) will return `sequencing_id` : ```curl -H "Accept: text/csv" localhost:5000/api/analyses\?user=1```
- _bulk now inserts `sequencing_id` into the database and returns it in the json : ```curl -XPOST -H 'Content-Type: text/csv' --data-binary @flask/tests/samplecsv.csv localhost:5000/api/_bulk\?user=1\&groups=cheo```

Flask: fix sequencing_id in _bulk and GET analyses

---

.gitattributes

oops, this made Git try to "normalize line endings" in images

gitattributes: don't treat all files as text

---

.github/workflows/flask.yml
docker-compose.cheo.yaml

Third time's the charm? #862 #877
- Use docker/metadata-action to infer image tags and labels
- Use docker/build-push-action twice to build the dev image, then test, then push. The second use will simply push from the cache
- Create a new deploy job that depends on a separate environment holding backend secrets
- Create a new Compose file for this deployment to CHEO-RI that just has a backend container on a single host, which supersedes the one in cheo-ri-infrastructure/stager. I've collapsed the database credentials into one secret to make it easier to manage
The successful run: https://github.com/ccmbioinfo/stager/runs/3910343642

CI: rewrite backend workflow to be push-based

---

docker-compose.oidc.yaml
docker-compose.prod.yaml
docker-compose.test.yaml
docker-compose.yaml

The combination of MINIO_UPDATE=off AND --quiet is required to prevent calling home in this instance
This means we lose all startup messages and logs
Forward the Console port for MinIO releases since 20210617
Freeze version due to regression in 20211105 (no release notes) discovered by Jenny

Docker: disable MinIO update check at startup, forward Console port, freeze version

---

docker-compose.test.yaml
flask/app/utils.py
react/src/functions.tsx

When we save changes in the modals and if there are no changes in the field values, the `updated` timestamp would still change. This is caused by either a nonnull `library_prep_date` field or a nonnull `month_of_birth` field. When the backend receives the JSON request, the values for these fields are of type String. However, the values of these fields are stored in the database as `DateTime.Date()` object. Thus, when we commit the session, SQLAlchemy will think that there's a change in data values and update the timestamp. 
The solution presented here is to convert the values from `String` type to `DateTime.Date()` type in the backend.

Flask: Fix updated timestamp in the modals.

---

.github/workflows/flask.yml
flask/app/groups.py
flask/app/madmin.py
flask/app/manage.py
flask/tests/test_groups.py

Update policy to include 'results-CODENAME'
Deny group codes starting with 'results-'
Add Click command 'migrate-minio-policies' to retroactively update existing groups
Objects will have to be moved to the correct bucket after the migration
Fix order of input validation for POST and PATCH endpoints
Closes #874
Missing

Flask: separate MinIO upload bucket from results bucket

---

react/public/index.html
react/src/AddDatasets/components/DataEntryToolbar.tsx
react/src/Settings/components/Instructions.tsx
react/src/Settings/index.tsx

Please check if I missed any. To observe the behaviour change, open the developer tools, disable cache, and click on outbound links. There should be no `Referer:` header. This should also be true for the two font requests on a hard reload.
Documentation:
https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer
https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-referrerpolicy

React: use no-referrer globally and for all external links

---

flask/app/participants.py
react/src/hooks/datasets/useDatasetUpdateMutation.tsx
react/src/hooks/participants/useParticipantQuery.tsx
react/src/hooks/participants/useParticipantsPage.tsx

Fixed bug: if a dataset's type is updated in the Dataset table or Dataset modal, the corresponding change is not reflected in the Participant table or Participant modal if we don't refresh the Participant page.

React: fix dataset types going out of sync between the Dataset and Participant modals

---

flask/app/analyses.py
flask/app/datasets.py
flask/tests/conftest.py
flask/tests/test_analyses.py
react/src/Analyses/index.tsx
react/src/Datasets/components/DatasetTable.tsx
react/src/components/AnalysisInfoDialog.tsx
react/src/components/ExactMatchFilterToggle.tsx
react/src/functions.tsx
react/src/hooks/analyses/useAnalysisCreateMutation.tsx
react/src/hooks/analyses/useAnalysisUpdateMutation.tsx
react/src/hooks/datasets/useDatasetsPage.tsx
react/src/typings.tsx

1. In `Dataset` modal and table, disable a dataset's ` dataset_type` editing if there's an analysis associated with it. Now the user can't change a `dataset_type` once there's an analysis associated with it.
2. Display all analyses, including the ones that don't have an assignee.
3. Fix the table nonrefreshing issue when a re-analysis is requested through the dialogue.
4. Fix the table nonrefreshing issue when an analysis is cancelled.
Other issues to be addressed in another ticket: 
- When the user selects an analysis and performs any of the following actions: run, complete, error, set assignee, the status is not reflected immediately.  For some of these actions, the snackbar would not even show up. My preliminary investigation for the action `Run Analysis` reveals that this is due to …

React/Flask: Add condition to dataset_type editability, fix Analyses table part I. 

---

flask/app/routes.py
flask/tests/test_misc.py

1. Abort the transaction when either 1) one of the newly uploaded datasets is a duplicate of an existing dataset or 2) there are duplicates among the newly uploaded datasets. The combination of unique fields is: `participant_id`-`family_id`-`tissue_sample_type`-`dataset_type`-`sequencing_date`.
2. Added unit tests. Changed a few existing unit tests to avoid errors raised by duplicate datasets. 
3. Changed line 472 in `routes.py` to `db.session.flush`
Observation: `sequencing_date` of a dataset is not shown in the dataset table nor in the dataset modal. Maybe the reason is that this is a piece of information that the user should not have access to?

Flask: Check for duplicate datasets

---

flask/app/datasets.py
flask/tests/test_datasets.py

Addresses issue #941. 
As a side note, this is how we handle `tissue_sample` when a dataset is deleted, in the master branch:[ link ](https://github.com/ccmbioinfo/stager/blob/e0bbcdf717e25fba568e0b8674f02031e5a2db6e/flask/app/datasets.py#L378)
This is how I handle it in this PR:[ link ](https://github.com/ccmbioinfo/stager/blob/9012059f07a199c8684fb07bb0eb3550ac089f11/flask/app/datasets.py#L378)
You can see that my approach is different in the sense that I don’t check `dataset_id` when looping through tissue_sample’s datasets. This is because I get rid of joinedLoad.
I prefer my approach because it's clearer as to what to expect, in the sense of SQLAlchemy queries. Feel free to let me know if the old approach is what we want. 
Closes #941

Flask: Remove related objects when a dataset is deleted. 

---

.github/workflows/flask.yml
docker-compose.cheo.yaml
flask/utils/run.sh

Interim experimental solution to the server process choking out until we determine root cause

Docker: use single-threaded Gunicorn workers scaled to the number of cores

---

react/src/App.tsx

If `labs.json` does not exist, the index page will be returned instead, which the processing code can't handle.

React: disable fetch to labs.json

---

flask/requirements-dev.txt
flask/requirements.txt

Dependabot identified an issue with incompatible with `starbank` dependency. Upgrading sendgrid to the latest version resolved this.

Flask: fix security warning for 'starbank'

---

flask/app/buckets.py
react/src/AddDatasets/components/DataEntryTable.tsx
react/src/AddDatasets/components/TableCells.tsx
react/src/AddDatasets/components/utils.tsx
react/src/Datasets/components/DatasetTable.tsx
react/src/components/AutocompleteMultiselect.tsx
react/src/components/FieldDisplayEditable.tsx
react/src/components/FileLinkingComponent.tsx
react/src/hooks/index.tsx
react/src/hooks/unlinked/useUnlinkedFilesQuery.tsx
react/src/hooks/useDebounce.ts

- We've seen that when the unlinked file payload is very large (>2MB), it takes a long time for all files to be returned, leading to a laggy user experience. 
- I modified the `get_unlinked_files` function to only return results based on prefixes. This is per Hannah Driver's feedback since she usually already knows what files she has to pass in, and uses the prefix in stager as a way to type in the right file faster and more accurately.
- The frontend was also modified to only return results based on the prefixes that user types.

Flask/React: update /api/unlinked to query by prefix only, debounce requests on frontend

---

react/public/sample.labs.json
react/src/AddDatasets/components/DataEntryToolbar.tsx
react/src/App.tsx
react/src/Settings/components/Instructions.tsx
react/src/Settings/index.tsx
react/src/components/LabDropdownSelect.tsx
react/src/hooks/utils.tsx
react/src/typings.tsx

A field `minio_endpoint` is added to `labs.json` specifying the MinIO URL for a specific lab tenant. This value will override any environment value. 
The current implementation still supports a single instance development environment, where the file `labs.json` is non-existent.

React: Dynamic MinIO URL

---

react/src/hooks/analyses/useAnalysisCreateMutation.tsx

Cause is an extraneous 'type' parameter that is only used in the frontend

React: fix analysis requests broken by backend schema verification

---

.gitignore
docker-compose.ccm.yaml
docker-compose.yaml
nginx/conf.d/default.conf
traefik/frontend.yml
traefik/https.yml

This is already working on the real site. Please check if the configuration makes sense and if additional documentation is needed beyond [Traefik's own](https://doc.traefik.io/traefik/).
Closes #976

Docker: switch to Traefik for multitenant deployment

---

.github/workflows/react.yml

The `yarn install` step should never be skipped as directly caching `node_modules` leads to funny behaviour.

CI: fix caching behaviour for frontend workflow

---

flask/app/buckets.py

Before, we could only search if a file exists by full file path. 
Now, if user types in a bucket name followed by a file prefix, they should be able to see a list of files under that bucket. For example, typing in "c4r/exome" should show results such as "c4r/exome/testfile1.bam", "c4r/exome/testfile2.bam", etc.

Flask: fix /api/unlinked to allow for prefix searches

---

flask/app/madmin.py

Deny overrides Allow, so change the per-group policy to use explicit Allows. All policies: https://docs.min.io/minio/baremetal/security/minio-identity-management/policy-based-access-control.html
I will run `migrate-minio-policies` after merging.

Flask: fix admins not having MinIO delete permissions

---

Dockerfile
flask/Dockerfile
flask/tests/test_misc.py
flask/tests/unit/test_json_validation_decorator.py

The use of `@patch()` from `unittest.mock` module for mocking request context does not raise any problem when using Python3.7. By switching to Python 3.8, we will get "RuntimeError: Working outside of request context." 
Potential causes: 
1, Python 3.8 has added support for asynchronous code testing. This runtime error might be due to the added support for mocking asynchronous code in Python 3.8 as explained here: [link](https://github.com/pallets/flask/issues/3637#issuecomment-655372502).
2, `@patch` namespace resolution. 
The solution in this PR: 
Use [Flask testing approaches](https://flask.palletsprojects.com/en/2.0.x/testing/#other-testing-tricks) for `test_must_pass_in_user_argument_if_login_disabled`, `test_validate_json_throws_415_on_non_json_header` and …

Flask: upgrade to Python 3.8 

---

react/yarn.lock

All resolved by re-resolving CRA dependencies (yarn upgrade react-scripts), though the vulnerabilities aren't actually on the live codepath.
Can confirm with `yarn audit` that there are no complaints now.

React: fix security warnings

---

Dockerfile
flask/Dockerfile
flask/app/schemas.py
flask/tests/test_misc.py
flask/tests/unit/test_json_validation_decorator.py

This PR is a continuation of #1028 . In production, `wsgi` import raised an error because the module import `typing_extensions` in `schemas.py` can't be found. With this PR, simulating the production environment with `docker-compose up app_gunicorn` raised no errors.

Flask: Upgrade to python 3.8 (again)

---

flask/app/madmin.py

--watch seems to additionally depend on the Bucket Notifications API https://docs.min.io/minio/baremetal/security/minio-identity-management/policy-based-access-control.html
Fixes regression introduced in #1012

Flask: fix mc mirror --watch failing with Access Denied

---

flask/app/manage.py

Fixes some click commands not working because MINIO_TLS wasn't considered
Repeat of #1027 after #1030 revert. Prod failure was caused by #1028, reverted #1031

 Flask: make most initializations of MinIO client SDKs consistent

---

traefik/https.yml

Require TLS 1.2+ and only secure ciphers
From a security warnning issued by RIT/HPF. Check at https://www.ssllabs.com/ssltest/analyze.html?d=stager.ccm.sickkids.ca&hideResults=on or with `nmap --script ssl-enum-ciphers -p 443 stager.ccm.sickkids.ca`
Note: I already made this change effective in production

Traefik: improve TLS

---

Dockerfile
README.md
docs/docker.md
docs/flask.md
docs/locust.md
flask/Dockerfile

Here are some main new features and security improvements in Python 3.9: [Link](https://towardsdatascience.com/10-awesome-python-3-9-features-b8c27f5eba5c).  
Python 3.9 is in the Ubuntu Focal distro's repos:[ link](https://packages.ubuntu.com/focal/python3.9). However, Python 3.8 is still the default system choice for Ubuntu.

Flask: Upgrade from Python 3.8 to Python 3.9

---

docker-compose.ccm.yaml
docs/production.md
traefik/frontend.yml
traefik/https.yml
traefik/traefik-api.yml

Reverse proxying to MinIO forwarded HSTS headers, so we'll implement HTTPS and HSTS for every service as it affects the entire primary domain already.
Refactor all HTTP security-related headers into the `security` middleware to reuse across all routers.
Configure the Traefik entrypoint to use port 8443 instead of 8080 and enable TLS. This will serve the main Traefik API and dashboard on the main domain, and proxy to the Prometheus endpoint of each backend on the corresponding backend domains. To implement this, an additional router is configured per service for the 8080 Gunicorn metrics port, since Traefik only automatically configures one service (port) per container.

Traefik: switch internal API, metrics to HTTPS/8443, enable HSTS

---

flask/app/buckets.py
react/src/components/AutocompleteMultiselect.tsx
react/src/hooks/unlinked/useUnlinkedFilesQuery.tsx

The goal of this PR is to reduce the `unlinked` file's endpoint payload. 
The main changes in this PR are:
- Set `recursive` property to `false`
- Added a check to see if an option is a file or folder. If it's a folder, autocomplete the folder path and sends off a query. If not, then the file is selected as an unlinked file.

Flask: made unlinked file query non-recursive to reduce payload

---

.github/workflows/flask-rollback.yml

This adds a manually-triggered workflow in the Actions tab that will allow us to roll back the backend quickly without having to rebuild and retest a prior commit.

CI: add backend rollback workflow

---

flask/app/analyses.py
flask/app/datasets.py
flask/app/families.py
flask/app/groups.py
flask/app/participants.py
flask/app/routes.py
flask/app/tissue_samples.py
flask/app/users.py

Error messages from Marshmallow validation are jsonified for logging. They should not be jsonified to output a human-readable error message in logging.

Flask: Fix Marshmallow validation error logging 

---

react/src/AddDatasets/components/TableCells.tsx
react/src/Datasets/components/DatasetTable.tsx
react/src/components/FieldDisplay.tsx
react/src/components/TooltipDatasetType.tsx
react/src/components/index.tsx

Closes #1074 
Human-readable names for dataset types are added at the following places:

React: Display human-readable names for dataset types

---

react/src/components/AutocompleteMultiselect.tsx

Fixes #1075
Regression seems to have been introduced in https://github.com/ccmbioinfo/stager/pull/1029 as the AutocompleteMultiselect component is also used by CandidateGeneCell

React: fix candidate genes dropdown

---

flask/requirements-dev.txt
flask/requirements.in
flask/requirements.txt

There's a lot, so I rolled them up into one
New:
- setproctitle: https://docs.gunicorn.org/en/latest/faq.html#how-can-i-name-processes
Primary dependencies:
- flask
- flask-login
- minio
- prometheus-flask-exporter
- sqlalchemy

Flask: package upgrade
